import { DashboardHeader } from "@/components/DashboardHeader";
import { DashboardFooter } from "@/components/DashboardFooter";
import { AlertsWidget } from "@/components/AlertsWidget";
import { CO2Widget } from "@/components/CO2Widget";
import { CostSavingsCalculator } from "@/components/CostSavingsCalculator";
import { RealVsSimulatedChart } from "@/components/RealVsSimulatedChart";
import { IoTDataFeed } from "@/components/IoTDataFeed";
import { useLanguage } from "@/contexts/LanguageContext";
import { useSolarConfig } from "@/hooks/useSolarConfig";
import { useAuthGuard } from "@/hooks/useAuthGuard";
import { useActualProduction } from "@/hooks/useActualProduction";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import { useSolarProduction } from "@/hooks/useSolarProduction";
import jsPDF from "jspdf";
import "jspdf-autotable";

const IoTSection = () => {
  const { isConnected, loading } = useActualProduction();
  if (loading || !isConnected) return null;
  return (
    <section className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      <RealVsSimulatedChart />
      <IoTDataFeed />
    </section>
  );
};

const Reports = () => {
  const { config } = useSolarConfig();
  const { t } = useLanguage();
  const { authLoading, handleLogout, AuthLoadingScreen } = useAuthGuard();
  const { production } = useSolarProduction(config.panelSize, config.azimuth, config.tilt);
  const hourlyData = production.hourlyData.map((d) => ({ hour: d.time, production: d.energy }));

  const downloadPDF = () => {
    const doc = new jsPDF();
    const today = new Date().toLocaleDateString("en-IN", { dateStyle: "long" });

    // Header
    doc.setFontSize(20);
    doc.setTextColor(33, 53, 85);
    doc.text("Sun Peek Insight", 14, 20);
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text(`Daily Energy Production Report — ${today}`, 14, 28);

    // System info
    doc.setFontSize(10);
    doc.setTextColor(60);
    doc.text(`System Capacity: ${config.panelSize} kW | Azimuth: ${config.azimuth}° | Tilt: ${config.tilt}°`, 14, 38);

    // Summary
    const totalEnergy = hourlyData.reduce((sum, d) => sum + d.production, 0);
    const peakPower = Math.max(...hourlyData.map((d) => d.production));
    const avgPower = totalEnergy / Math.max(hourlyData.filter((d) => d.production > 0).length, 1);

    doc.setFontSize(11);
    doc.setTextColor(33, 53, 85);
    doc.text("Summary", 14, 50);
    doc.setFontSize(10);
    doc.setTextColor(60);
    doc.text(`Total Energy: ${totalEnergy.toFixed(2)} kWh`, 14, 58);
    doc.text(`Peak Power: ${peakPower.toFixed(2)} kW`, 14, 64);
    doc.text(`Average Output: ${avgPower.toFixed(2)} kW`, 14, 70);
    doc.text(`CO₂ Offset: ${(totalEnergy * 0.82).toFixed(2)} kg`, 14, 76);
    doc.text(`Estimated Savings: ₹${(totalEnergy * 8.5).toFixed(2)}`, 14, 82);

    // Hourly table
    const tableData = hourlyData.map((d) => [d.hour, `${d.production.toFixed(2)} kW`, `${(d.production * 0.82).toFixed(2)} kg`]);

    (doc as any).autoTable({
      startY: 92,
      head: [["Hour", "Production (kW)", "CO₂ Offset (kg)"]],
      body: tableData,
      theme: "striped",
      headStyles: { fillColor: [33, 53, 85], textColor: 255 },
      styles: { fontSize: 9 },
    });

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by Sun Peek Insight — sun-peek-insight.lovable.app", 14, pageHeight - 10);

    doc.save(`SunPeekInsight_Report_${new Date().toISOString().split("T")[0]}.pdf`);
  };

  if (authLoading) return <AuthLoadingScreen />;

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <DashboardHeader onLogout={handleLogout} />

      <section className="border-b border-border/40">
        <div className="container mx-auto px-4 py-8 flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-foreground">{t("navReports")}</h1>
            <p className="text-muted-foreground mt-1 text-sm">{t("reportsSubtitle")}</p>
          </div>
          <Button onClick={downloadPDF} variant="outline" size="sm" className="gap-2">
            <Download className="h-4 w-4" />
            Download PDF
          </Button>
        </div>
      </section>

      <main className="flex-1 container mx-auto px-4 py-8 space-y-8">
        <IoTSection />
        <section className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <AlertsWidget />
          <CO2Widget systemCapacity={config.panelSize} azimuth={config.azimuth} tilt={config.tilt} />
          <CostSavingsCalculator systemCapacity={config.panelSize} />
        </section>
      </main>

      <DashboardFooter />
    </div>
  );
};

export default Reports;
