import { Battery, Zap, TrendingUp, Sun, Info } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { useSolarProduction } from "@/hooks/useSolarProduction";
import { Skeleton } from "@/components/ui/skeleton";
import { useState } from "react";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

interface EnergyStatsProps {
  systemCapacity: number;
  azimuth?: number;
  tilt?: number;
}

export const EnergyStats = ({ systemCapacity, azimuth = 180, tilt = 19 }: EnergyStatsProps) => {
  const { production, loading } = useSolarProduction(systemCapacity, azimuth, tilt);
  const [openTooltip, setOpenTooltip] = useState<number | null>(null);

  const productionStartTime = new Date();
  productionStartTime.setHours(6, 0, 0, 0); // Assumes production starts at 6 AM

  const stats = [
    {
      title: "Current Output",
      value: loading ? "..." : `${production.currentOutput} kW`,
      icon: Zap,
      trend: "+12%",
      color: "text-secondary",
      info: {
        startTime: productionStartTime.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
        summary: "Real-time power generation",
        mechanism: "Measures the instantaneous electrical power being generated by your solar panels right now. Calculated based on current sunlight intensity, panel orientation, and weather conditions."
      }
    },
    {
      title: "Today's Production",
      value: loading ? "..." : `${production.todayTotal} kWh`,
      icon: Sun,
      trend: "+8%",
      color: "text-accent",
      info: {
        startTime: productionStartTime.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
        summary: "Accumulated energy today",
        mechanism: "Total energy produced since sunrise. Integrates hourly power output throughout the day, accounting for sun position, cloud cover, and panel efficiency. Resets at midnight."
      }
    },
    {
      title: "System Efficiency",
      value: loading ? "..." : `${production.efficiency}%`,
      icon: Battery,
      trend: "+5%",
      color: "text-primary",
      info: {
        startTime: productionStartTime.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
        summary: "Panel performance rating",
        mechanism: "Percentage of optimal energy conversion based on panel orientation (azimuth & tilt). Compares actual output to theoretical maximum for your location. Optimal orientation for your latitude yields 100% efficiency."
      }
    },
    {
      title: "Monthly Total",
      value: loading ? "..." : `${production.monthlyTotal} kWh`,
      icon: TrendingUp,
      trend: "+15%",
      color: "text-secondary",
      info: {
        startTime: new Date(new Date().getFullYear(), new Date().getMonth(), 1).toLocaleDateString('en-US', { month: 'long', day: 'numeric' }),
        summary: "Total energy this month",
        mechanism: "Cumulative energy production from the 1st of the month. Aggregates daily totals while factoring in seasonal sun patterns, weather variations, and system performance. Useful for billing and ROI tracking."
      }
    },
  ];

  return (
    <TooltipProvider>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        {stats.map((stat, index) => (
          <Card
            key={index}
            className="border-border/50 premium-glass shadow-card hover:shadow-premium transition-all duration-500 hover:scale-[1.03] hover:-translate-y-2 group"
          >
            <CardContent className="p-7">
              <div className="flex items-start justify-between mb-5">
                <div className={`p-4 rounded-2xl bg-gradient-to-br from-primary/15 to-accent/15 shadow-lg ${stat.color} transition-all duration-300 group-hover:scale-110 group-hover:shadow-glow`}>
                  <stat.icon className="h-7 w-7 drop-shadow-lg" />
                </div>
                <span className="text-xs font-bold text-green-500 bg-gradient-to-r from-green-500/25 to-green-500/15 px-4 py-2 rounded-full border border-green-500/30 shadow-sm">
                  {stat.trend}
                </span>
              </div>
              <div className="flex items-center justify-between mb-1">
                <h3 className="text-sm font-medium text-muted-foreground">
                  {stat.title}
                </h3>
                <Tooltip open={openTooltip === index} onOpenChange={(open) => setOpenTooltip(open ? index : null)}>
                  <TooltipTrigger asChild>
                    <button 
                      onClick={(e) => {
                        e.preventDefault();
                        setOpenTooltip(openTooltip === index ? null : index);
                      }}
                      className="text-muted-foreground hover:text-foreground transition-colors"
                    >
                      <Info className="h-4 w-4" />
                    </button>
                  </TooltipTrigger>
                  <TooltipContent className="max-w-xs p-4 bg-popover border border-border z-50">
                    <div className="space-y-2">
                      <div className="flex items-center gap-2 text-xs text-muted-foreground">
                        <span className="font-semibold">Started:</span>
                        <span>{stat.info.startTime}</span>
                      </div>
                      <div>
                        <p className="font-semibold text-sm text-foreground mb-1">{stat.info.summary}</p>
                        <p className="text-xs text-muted-foreground leading-relaxed">{stat.info.mechanism}</p>
                      </div>
                    </div>
                  </TooltipContent>
                </Tooltip>
              </div>
              {loading ? (
                <Skeleton className="h-9 w-28" />
              ) : (
                <p className="text-3xl font-bold text-foreground tracking-tight">{stat.value}</p>
              )}
            </CardContent>
          </Card>
        ))}
      </div>
    </TooltipProvider>
  );
};
