import { Battery, Zap, TrendingUp, Sun, Info } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { useSolarProduction } from "@/hooks/useSolarProduction";
import { Skeleton } from "@/components/ui/skeleton";
import { useState } from "react";
import { useLanguage } from "@/contexts/LanguageContext";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

interface EnergyStatsProps {
  systemCapacity: number;
  azimuth?: number;
  tilt?: number;
}

export const EnergyStats = ({ systemCapacity, azimuth = 180, tilt = 19 }: EnergyStatsProps) => {
  const { production, loading } = useSolarProduction(systemCapacity, azimuth, tilt);
  const [openTooltip, setOpenTooltip] = useState<number | null>(null);
  const { t } = useLanguage();

  const productionStartTime = new Date();
  productionStartTime.setHours(6, 0, 0, 0);

  const stats = [
    {
      title: t("currentOutput"),
      value: loading ? "..." : `${production.currentOutput} kW`,
      icon: Zap,
      trend: "+12%",
      color: "text-secondary",
      info: {
        startTime: productionStartTime.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
        summary: t("realTimePower"),
        mechanism: "Measures the instantaneous electrical power being generated by your solar panels right now."
      }
    },
    {
      title: t("todaysProduction"),
      value: loading ? "..." : `${production.todayTotal} kWh`,
      icon: Sun,
      trend: "+8%",
      color: "text-accent",
      info: {
        startTime: productionStartTime.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
        summary: t("accumulatedEnergy"),
        mechanism: "Total energy produced since sunrise. Integrates hourly power output throughout the day."
      }
    },
    {
      title: t("systemEfficiency"),
      value: loading ? "..." : `${production.efficiency}%`,
      icon: Battery,
      trend: "+5%",
      color: "text-primary",
      info: {
        startTime: productionStartTime.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
        summary: t("panelPerformance"),
        mechanism: "Percentage of optimal energy conversion based on panel orientation (azimuth & tilt)."
      }
    },
    {
      title: t("monthlyTotal"),
      value: loading ? "..." : `${production.monthlyTotal} kWh`,
      icon: TrendingUp,
      trend: "+15%",
      color: "text-secondary",
      info: {
        startTime: new Date(new Date().getFullYear(), new Date().getMonth(), 1).toLocaleDateString('en-US', { month: 'long', day: 'numeric' }),
        summary: t("totalEnergyMonth"),
        mechanism: "Cumulative energy production from the 1st of the month."
      }
    },
  ];

  return (
    <TooltipProvider>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        {stats.map((stat, index) => (
          <Card
            key={index}
            className="relative z-0 border-border/50 bg-gradient-to-br from-card via-card to-card/80 backdrop-blur-sm shadow-card hover:shadow-card-hover transition-all duration-300 hover:scale-[1.02] hover:-translate-y-1 card-glow overflow-visible"
          >
            <CardContent className="p-6">
              <div className="flex items-start justify-between mb-4">
                <div className={`p-3 rounded-xl bg-gradient-to-br from-primary/10 to-accent/10 shadow-md ${stat.color} transition-transform duration-300 hover:scale-110`}>
                  <stat.icon className="h-6 w-6 drop-shadow" />
                </div>
                <span className="text-xs font-semibold text-green-500 bg-gradient-to-r from-green-500/20 to-green-500/10 px-3 py-1.5 rounded-full border border-green-500/20">
                  {stat.trend}
                </span>
              </div>
              <div className="flex items-center justify-between mb-1">
                <h3 className="text-sm font-medium text-muted-foreground">
                  {stat.title}
                </h3>
                <Tooltip open={openTooltip === index} onOpenChange={(open) => setOpenTooltip(open ? index : null)}>
                  <TooltipTrigger asChild>
                    <button 
                      onClick={(e) => {
                        e.preventDefault();
                        setOpenTooltip(openTooltip === index ? null : index);
                      }}
                      className="text-muted-foreground hover:text-foreground transition-colors"
                    >
                      <Info className="h-4 w-4" />
                    </button>
                  </TooltipTrigger>
                  <TooltipContent className="max-w-xs p-4 bg-popover border border-border z-[60]">
                    <div className="space-y-2">
                      <div className="flex items-center gap-2 text-xs text-muted-foreground">
                        <span className="font-semibold">{t("started")}</span>
                        <span>{stat.info.startTime}</span>
                      </div>
                      <div>
                        <p className="font-semibold text-sm text-foreground mb-1">{stat.info.summary}</p>
                        <p className="text-xs text-muted-foreground leading-relaxed">{stat.info.mechanism}</p>
                      </div>
                    </div>
                  </TooltipContent>
                </Tooltip>
              </div>
              {loading ? (
                <Skeleton className="h-8 w-24" />
              ) : (
                <p className="text-2xl font-bold text-foreground">{stat.value}</p>
              )}
            </CardContent>
          </Card>
        ))}
      </div>
    </TooltipProvider>
  );
};
